# Generated by Django 5.1.5 on 2026-08-22 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_ensure_government_id_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_cuisines',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='food_connection_preferences',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
