# Generated by Django 5.1.5 on 2026-08-28 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_feedback_homepagevideo_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional rating from 1 to 5.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='homepagevideo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If enabled, this video can be displayed on the FoodKindl homepage.'),
        ),
        migrations.AddConstraint(
            model_name='feedback',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='feedback_rating_between_1_and_5'),
        ),
    ]
