# Generated by Django 5.1.5 on 2026-09-15 16:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CookTogether',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('dish', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=180)),
                ('exact_address', models.TextField(blank=True)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='cook_together/covers/%Y/%m/')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10)),
                ('verified_only', models.BooleanField(default=True)),
                ('women_only', models.BooleanField(default=False)),
                ('host_approval_required', models.BooleanField(default=True)),
                ('maximum_guests', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('dietary_notes', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cook_togethers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CookTogetherRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cook_together', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='cooktogether.cooktogether')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cook_together_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('cook_together', 'guest'), name='unique_cook_together_guest')],
            },
        ),
    ]
