# Generated by Django 5.1.5 on 2026-09-15 17:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooktogether', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cooktogether',
            name='invited_members',
            field=models.ManyToManyField(blank=True, related_name='cook_together_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
