# Generated by Django 5.1.5 on 2026-09-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cooktogether', '0002_cooktogether_invited_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cooktogetherrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='cooktogetherrequest',
            name='invitation_type',
            field=models.CharField(choices=[('join_request', 'Join request'), ('host_invite', 'Host invitation')], default='join_request', max_length=20),
        ),
        migrations.AddField(
            model_name='cooktogetherrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
