# Generated by Django 5.1.5 on 2026-09-16 16:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DineOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('restaurant_external_id', models.CharField(blank=True, max_length=120)),
                ('restaurant_name', models.CharField(max_length=220)),
                ('restaurant_address', models.TextField(blank=True)),
                ('restaurant_cuisine', models.CharField(blank=True, max_length=180)),
                ('restaurant_phone', models.CharField(blank=True, max_length=50)),
                ('restaurant_website', models.URLField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('starts_at', models.DateTimeField()),
                ('maximum_guests', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('budget_label', models.CharField(blank=True, max_length=100)),
                ('booking_status', models.CharField(choices=[('not_booked', 'Not booked yet'), ('booked', 'Booked'), ('walk_in', 'Walk in')], default='not_booked', max_length=20)),
                ('dietary_notes', models.TextField(blank=True)),
                ('meetup_notes', models.TextField(blank=True)),
                ('verified_only', models.BooleanField(default=False)),
                ('women_only', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_dine_outs', to=settings.AUTH_USER_MODEL)),
                ('invited_members', models.ManyToManyField(blank=True, related_name='dine_out_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['starts_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DineOutResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dine_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='dineout.dineout')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dine_out_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dine_out', 'guest'), name='unique_dineout_guest_response')],
            },
        ),
    ]
