# Generated by Django 5.1.5 on 2026-09-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dineout', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dineoutresponse',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='dineout',
            name='visibility',
            field=models.CharField(choices=[('public', 'Visible to everyone'), ('invited_only', 'Selected guests only')], default='public', max_length=20),
        ),
    ]
