# Generated by Django 5.1.5 on 2026-08-22 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator_user_id', models.PositiveBigIntegerField(db_index=True)),
                ('invite_type', models.CharField(choices=[('cook_together', 'Cook Together'), ('dine_out', 'Dine Out'), ('food_walk', 'Food Walk')], db_index=True, max_length=30)),
                ('title', models.CharField(blank=True, default='', max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('cuisine', models.CharField(blank=True, default='', max_length=180)),
                ('start_at', models.DateTimeField(db_index=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('cook_venue_type', models.CharField(blank=True, choices=[('home', 'Home'), ('clubhouse', 'Clubhouse'), ('other', 'Other Venue')], default='', max_length=30)),
                ('dine_venue_type', models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe')], default='', max_length=30)),
                ('venue_name', models.CharField(blank=True, default='', max_length=200)),
                ('location_label', models.CharField(blank=True, default='', max_length=200)),
                ('private_address', models.CharField(blank=True, default='', max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('food_walk_stops', models.JSONField(blank=True, default=list)),
                ('max_participants', models.PositiveIntegerField(default=2)),
                ('verified_only', models.BooleanField(default=True)),
                ('women_only', models.BooleanField(default=False)),
                ('kitchen_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], db_index=True, default='open', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('start_at',),
            },
        ),
        migrations.CreateModel(
            name='FoodInviteParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveBigIntegerField(db_index=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined')], db_index=True, default='invited', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='invites.foodinvite')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('invite', 'user_id'), name='unique_food_invite_participant')],
            },
        ),
    ]
