# Generated by Django 5.1.5 on 2026-08-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('restaurant_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe')], default='restaurant', max_length=20)),
                ('cuisine', models.CharField(blank=True, max_length=180)),
                ('locality', models.CharField(blank=True, db_index=True, max_length=180)),
                ('city', models.CharField(blank=True, db_index=True, max_length=120)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-rating', 'name'],
            },
        ),
    ]
