# Generated by Django 5.1.5 on 2026-09-07 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_add_restaurant_owner_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='is_foodkindl_partner',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
