# Generated by Django 5.1.5 on 2026-09-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0004_foodinvite_latitude_foodinvite_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinvite',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodinvite',
            name='longitude',
            field=models.FloatField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantsubmission',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantsubmission',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
