# Generated by Django 5.1.5 on 2026-08-22 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0004_restaurant_accepts_foodkindl_booking_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodinvite',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='foodinvite',
            name='longitude',
        ),
    ]
