# Generated by Django 5.1.5 on 2026-09-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0005_alter_foodinvite_latitude_alter_foodinvite_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodinvite',
            name='dine_venue_type',
            field=models.CharField(blank=True, choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('hotel', 'Hotel'), ('bakery', 'Bakery')], default='', max_length=30),
        ),
    ]
