# Generated by Django 5.1.5 on 2026-08-23 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0006_remove_restaurant_image_remove_restaurant_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(blank=True, default='', help_text='Enter the full Netlify image URL.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='locality',
            field=models.CharField(blank=True, db_index=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_range',
            field=models.CharField(blank=True, choices=[('budget', 'Budget'), ('moderate', 'Moderate'), ('premium', 'Premium')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurantbooking',
            name='food_invite_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantbooking',
            name='special_request',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='caption',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='image_url',
            field=models.URLField(help_text='Enter the full Netlify image URL.', max_length=1000),
        ),
        migrations.CreateModel(
            name='RestaurantMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('starter', 'Starter'), ('main_course', 'Main Course'), ('bread', 'Bread'), ('rice', 'Rice'), ('dessert', 'Dessert'), ('beverage', 'Beverage'), ('snack', 'Snack'), ('other', 'Other')], default='main_course', max_length=30)),
                ('food_type', models.CharField(choices=[('vegetarian', 'Vegetarian'), ('non_vegetarian', 'Non Vegetarian'), ('vegan', 'Vegan'), ('egg', 'Egg')], default='vegetarian', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, default='', max_length=1000)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='invites.restaurant')),
            ],
            options={
                'ordering': ['sort_order', 'category', 'name'],
            },
        ),
    ]
