# Generated by Django 5.1.5 on 2026-08-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0007_alter_restaurant_address_alter_restaurant_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodinvite',
            options={'ordering': ['start_at']},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_blob_key',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_content_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image_original_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='image_blob_key',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='image_content_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='image_original_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='restaurantmenuitem',
            name='image_blob_key',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='restaurantmenuitem',
            name='image_content_type',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='restaurantmenuitem',
            name='image_original_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='average_cost_for_two',
            field=models.PositiveIntegerField(blank=True, help_text='Approximate cost for two people in INR.', null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1500),
        ),
        migrations.AlterField(
            model_name='restaurantmenuitem',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1500),
        ),
    ]
