# Generated by Django 5.1.5 on 2026-08-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0009_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, editable=False, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=6, editable=False, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='pincode',
            field=models.CharField(blank=True, db_index=True, default='', max_length=12),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['latitude', 'longitude'], name='restaurant_geo_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['is_active', 'is_foodkindl_partner', 'accepts_foodkindl_booking'], name='restaurant_partner_idx'),
        ),
    ]
