# Generated by Django 5.1.5 on 2026-08-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0010_alter_restaurant_latitude_alter_restaurant_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('south_indian', 'South Indian'), ('north_indian', 'North Indian'), ('kerala', 'Kerala'), ('karnataka', 'Karnataka'), ('tamil', 'Tamil'), ('andhra', 'Andhra'), ('telangana', 'Telangana'), ('hyderabadi', 'Hyderabadi'), ('punjabi', 'Punjabi'), ('bengali', 'Bengali'), ('rajasthani', 'Rajasthani'), ('gujarati', 'Gujarati'), ('maharashtrian', 'Maharashtrian'), ('goan', 'Goan'), ('kashmiri', 'Kashmiri'), ('chinese', 'Chinese'), ('indo_chinese', 'Indo-Chinese'), ('italian', 'Italian'), ('continental', 'Continental'), ('mediterranean', 'Mediterranean'), ('mexican', 'Mexican'), ('thai', 'Thai'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('arabian', 'Arabian'), ('middle_eastern', 'Middle Eastern'), ('lebanese', 'Lebanese'), ('biryani', 'Biryani'), ('seafood', 'Seafood'), ('street_food', 'Street Food'), ('fast_food', 'Fast Food'), ('cafe', 'Cafe'), ('bakery', 'Bakery'), ('desserts', 'Desserts'), ('barbecue', 'Barbecue / Grill'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('jain', 'Jain'), ('multi_cuisine', 'Multi Cuisine'), ('other', 'Other')], db_index=True, default='', max_length=50),
        ),
    ]
