# Generated by Django 5.1.5 on 2026-08-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0011_alter_restaurant_cuisine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('hotel', 'Hotel')], default='restaurant', max_length=20),
        ),
    ]
