# Generated by Django 5.1.5 on 2026-08-25 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0012_alter_restaurant_restaurant_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('restaurant_type', models.CharField(choices=[('restaurant', 'Restaurant'), ('cafe', 'Cafe'), ('hotel', 'Hotel')], default='restaurant', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('cuisine', models.CharField(blank=True, choices=[('south_indian', 'South Indian'), ('north_indian', 'North Indian'), ('kerala', 'Kerala'), ('karnataka', 'Karnataka'), ('tamil', 'Tamil'), ('andhra', 'Andhra'), ('telangana', 'Telangana'), ('hyderabadi', 'Hyderabadi'), ('punjabi', 'Punjabi'), ('bengali', 'Bengali'), ('rajasthani', 'Rajasthani'), ('gujarati', 'Gujarati'), ('maharashtrian', 'Maharashtrian'), ('goan', 'Goan'), ('kashmiri', 'Kashmiri'), ('chinese', 'Chinese'), ('indo_chinese', 'Indo-Chinese'), ('italian', 'Italian'), ('continental', 'Continental'), ('mediterranean', 'Mediterranean'), ('mexican', 'Mexican'), ('thai', 'Thai'), ('japanese', 'Japanese'), ('korean', 'Korean'), ('arabian', 'Arabian'), ('middle_eastern', 'Middle Eastern'), ('lebanese', 'Lebanese'), ('biryani', 'Biryani'), ('seafood', 'Seafood'), ('street_food', 'Street Food'), ('fast_food', 'Fast Food'), ('cafe', 'Cafe'), ('bakery', 'Bakery'), ('desserts', 'Desserts'), ('barbecue', 'Barbecue / Grill'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('jain', 'Jain'), ('multi_cuisine', 'Multi Cuisine'), ('other', 'Other')], default='', max_length=50)),
                ('phone_number', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('website', models.URLField(blank=True, default='', max_length=500)),
                ('address', models.TextField(blank=True, default='')),
                ('locality', models.CharField(blank=True, db_index=True, default='', max_length=180)),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('pincode', models.CharField(blank=True, default='', max_length=12)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('price_range', models.CharField(blank=True, choices=[('budget', 'Budget'), ('moderate', 'Moderate'), ('premium', 'Premium')], default='', max_length=20)),
                ('average_cost_for_two', models.PositiveIntegerField(blank=True, null=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('accepts_cards', models.BooleanField(default=True)),
                ('family_friendly', models.BooleanField(default=True)),
                ('outdoor_seating', models.BooleanField(default=False)),
                ('wheelchair_accessible', models.BooleanField(default=False)),
                ('serves_vegetarian', models.BooleanField(default=True)),
                ('serves_non_vegetarian', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True, default='', max_length=1500)),
                ('image_blob_key', models.CharField(blank=True, default='', max_length=1000)),
                ('image_original_name', models.CharField(blank=True, default='', max_length=500)),
                ('image_content_type', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_submissions', to='invites.restaurant')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_submission_reviews', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
